### PR TITLE
Implement subprocess remote call

### PR DESCRIPTION
**Pull request by pmatos**
This allows a call to a SUT in a remote machine through ssh
Adds dependency on paramiko.

### CODE REVIEW

**Comment by renatahodovan** [comment]
If I understand correctly, then all you need is to copy some binaries to the remote device before fuzzing. This step is needed to be done only once, i.e., every time you cross-compile a new version of your SUT, correct? If this it the case, then this operation is needed to be put into the update job, instead of a SUT call. (Since the update job is executed as often as you define, while SUT call is executed for every test case.)
Performing the copy as part of the update job can be achieved by adapting the [update script](https://github.com/renatahodovan/fuzzinator-configs/blob/master/sut/jsc/jsc-update.sh) to execute the update/build/copy steps. To set the update period, you need to configure [jsc-sample.ini](https://github.com/renatahodovan/fuzzinator-configs/blob/master/sut/jsc/jsc-sample.ini#L15).

**Comment by akosthekiss** [comment]
Some additional comments.

- A SUT call can be more complex than a simple function. It can be any callable (e.g., a class with `__call__`.) What's more, it can be a context manager (i.e., a class with `__enter__` and `__exit__`). When a fuzz job is started (and whenever it finds an issue), the context of the SUT call is _entered_ and when the job is finished (or an issue is found), the context is _exited_. (See: https://github.com/renatahodovan/fuzzinator/blob/master/fuzzinator/job/fuzz_job.py#L46-L54) Why I'm mentioning this is because I see that you plan to use ssh connections, and it may not be efficient to set up the connection before and to tear it down after every test case. In such a scenario, `__enter__` could handle the connect and `__exit__` the disconnect.

- _"Also, would this be something that you would be interested in having in fuzzinator, or would you prefer if I do further development in a separate fork?"_: Note that there is a third option. You don't need to put every "building block" into fuzzinator in order to use them. Fuzzinator is modular. You may use its built-in building block, but you don't have to. E.g., you could have `RemoteSubprocessCall` in a separate project / python package, say, in `fuzzinator_igalia_jsc`, and assuming that the package is available in your python environment, you can have `call = fuzzinator_igalia_jsc.RemoteSubprocessCall` in your config files. I.e., you don't have to fork, you can keep the fuzzing framework and the building blocks specific to your use case separate.

**Comment by pmatos** [comment]
@akosthekiss @renatahodovan thanks for the comments on this. I should really brush up on my Python - forgot how I could use my own modules with fuzzinator. Will close this PR and work on a separate repo. If I get to something generic enough I will reopen a PR.

**Comment by pmatos** [comment]
I will be continuing work here: https://github.com/pmatos/jsc32-fuzz/tree/fuzzinator

**Comment by renatahodovan** [comment]
@pmatos Unfortunately the link you shared is not available for us (404 Page not found). Is it maybe a private repo?
In the meantime, I set up a [Gitter](https://gitter.im/inbugwetrust/fuzzinator) channel for Fuzzinator. If you need any help and you prefer IM to GH issues, then you can find us there, too.

**Comment by pmatos** [comment]
> @pmatos Unfortunately the link you shared is not available for us (404 Page not found). Is it maybe a private repo?
> In the meantime, I set up a [Gitter](https://gitter.im/inbugwetrust/fuzzinator) channel for Fuzzinator. If you need any help and you prefer IM to GH issues, then you can find us there, too.

Project visibility fixed. Thanks for setting up Gitter. See you there.

**Pull request closed without merging**
