### PR TITLE
Remove kill_process_tree and use communicate on the killed process

### PR DESCRIPTION
**Pull request by pmatos**
This ensures no zombie processes are left behind.

### CODE REVIEW

**Comment by pmatos** [comment]
This definitely does not look enough to me. There are other places using the same pattern but I am not sure I want to change it without further testing. 

Also wondering if there's a way to write a test to check if this leaves a zombie process around. Issue is, in general, zombies are reaped straight away by init, which is why I only noticed it inside a docker container without an init process.

**Comment by pmatos** [comment]
@renatahodovan Do you think this kind of solution makes sense? Should I extend it to all other methods using this pattern. Would this mean I can remote `kill_process_tree` safely?

**Comment by renatahodovan** [comment]
@pmatos The current solution with `kill_process_tree` was introduced to ensure killing all the child processes on Windows. A similar solution was suggested [here](https://stackoverflow.com/questions/1230669/subprocess-deleting-child-processes-in-windows), too (even if it's an old post).

However, one possible shortcoming of the current implementation arised while reading the [documentation](https://psutil.readthedocs.io/en/latest/#psutil.wait_procs) and introspecting the code of Fuzzinator: at [this](https://github.com/renatahodovan/fuzzinator/blob/master/fuzzinator/controller.py#L491) point we wait a second for the child processes to terminate, however we don't check if all of them have successfully terminated. So, we should iterate through the result of `wait_procs` alive children and kill them one-by-one, just like the above psutil documentation suggests. This would be the smallest change and - if it works - the preferable one as well.

The biggest problem with any of the possible solutions is that it's quite hard to write a cross-platform test with mock SUTs to validate if it works correctly. So if you have some great idea how they could be tested then I'd be glad to hear about. Or if you have a reproducible real life use-case where you can try out these options, then please share your experience.

**Comment by renatahodovan** [comment]
Note: I tried to switch to the officially suggested `subprocess.run()` method instead of using raw Popen calls. The most tempting reason doing this was that `subprocess.run()` is a higher level API which still uses Popen, but hides the `communicate` calls and also handles timeout issues: 

> If the timeout expires, the child process will be killed and waited for.

I.e., no need for manual `kill` and `communicate` in timeout handling. Unfortunately, practice showed that it still leaves zombies behind while fuzzing multiprocess applications. So, if I'm not wrong, this approach won't work.

Source: https://docs.python.org/3/library/subprocess.html#subprocess.run

**Comment by renatahodovan** [comment]
@pmatos Scratch that, it seems that `subprcess.run()` works. I had an error in my environment in my previous trial.  `kill_process_tree` was replaced in #4a679d0746169bf2923d8a807ffccda430b94f7a at multiple places.

**Pull request closed without merging**
